name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version_override:
        description: 'Version Number'     
        required: true
        default: '0.0.0'


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Update commit version
      run: |
        $path = "${{ github.workspace }}"
        $filePathToTask = Join-Path -Path $path -ChildPath  "Sample.nuspec"
        Write-Host $filePathToTask
        $xml = New-Object XML
        $xml.Load($filePathToTask)
        $ns = New-Object System.Xml.XmlNamespaceManager($xml.NameTable)
        $ns.AddNamespace("ns", $xml.DocumentElement.NamespaceURI)
        $element =  $xml.DocumentElement.SelectSingleNode("//ns:repository", $ns)
        $element.commit = (git rev-parse HEAD).ToString()
        $xml.Save($filePathToTask)
        Write-Host (git rev-parse HEAD).ToString()
    - name: Package
      run: nuget pack Sample.nuspec -Symbols -SymbolPackageFormat snupkg
      
    - name: Deploy to nuget
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
